//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by resources.rc
//
#define IDW_MAIN                        41
#define IDW_ABOUT                       42

#define IDW_MAIN_ANSI                   2041
#define IDW_MAIN_COMPAT                 3041

#define IDM_FILE_EXIT                   110
#define IDM_EDIT_COPY                   111
#define IDM_EDIT_CLEAR                  112
#define IDM_HELP_ABOUT                  113
#define IDB_LOGO                        132
#define IDM_TRAY                        134
#define IDM_TRAY_OPEN                   135
#define IDM_TRAY_EXIT                   136

#define IDS_LOG_FORMAT_DATETIME         80
#define IDS_LOG_SEVERITY_FATAL          81
#define IDS_LOG_SEVERITY_ERROR          82
#define IDS_LOG_SEVERITY_WARNING        83
#define IDS_LOG_SEVERITY_INFO           84
#define IDS_LOG_SEVERITY_DEBUG          85
#define IDS_LOG_SEVERITY_VERBOSE        86

#define IDS_ABOUT_INFO                  900
#define IDS_ABOUT_INFO_OPEN_SOURCE      901
#define IDS_ABOUT_INFO_PROPRIETARY      902
#define IDS_ABOUT_INFO_FREEWARE         903
#define IDS_ABOUT_INFO_INTERNAL         904
#define IDS_ABOUT_DISCLAIMER            905

#define IDS_NOTICE_TCP_SERVER_STARTED   1000
#define IDS_NOTICE_UDP_SERVER_STARTED   1001
#define IDS_NOTICE_UDP_LEGACY_SERVER_STARTED 1002
#define IDS_ERROR_TCP_SERVER_CREATE     1200
#define IDS_ERROR_TCP_SERVER_BIND       1201
#define IDS_ERROR_TCP_SERVER_LISTEN     1202
#define IDS_ERROR_TCP_SERVER_ASYNC      1203
#define IDS_ERROR_UDP_SERVER_CREATE     1204
#define IDS_ERROR_UDP_SERVER_BIND       1205
#define IDS_ERROR_UDP_SERVER_ASYNC      1206
#define IDS_ERROR_UDP_LEGACY_SERVER_CREATE 1207
#define IDS_ERROR_UDP_LEGACY_SERVER_BIND 1208
#define IDS_ERROR_UDP_LEGACY_SERVER_ASYNC 1209
#define IDS_CLIENT_CONNECTED            1400
#define IDS_CLIENT_CONNECTED_ADDRESS    1401
#define IDS_CLIENT_DISCONNECTED         1402
#define IDS_CLIENT_DISCONNECTED_NET_DOWN 1403
#define IDS_CLIENT_DISCONNECTED_RESET   1404
#define IDS_CLIENT_DISCONNECTED_TIMEOUT 1405
#define IDS_CLIENT_DISCONNECTED_HEADER  1406
#define IDS_CLIENT_DISCONNECTED_INPUT_BUFFER 1407
#define IDS_CLIENT_DISCONNECTED_OUTPUT_BUFFER 1408
#define IDS_CLIENT_DISCONNECTED_BUILD   1409
#define IDS_CLIENT_DISCONNECTED_UNKNOWN 1410
#define IDS_CLIENT_DISCONNECTED_DEFAULT 1411
#define IDS_CLIENT_INPUT_UNKNOWN        1500
#define IDS_CLIENT_DEBUG_READ_VARIABLE_ASCII 1501
#define IDS_CLIENT_DEBUG_READ_VARIABLE_ASCIIW 1502
#define IDS_CLIENT_DEBUG_WRITE_VARIABLE_ASCII 1503
#define IDS_CLIENT_DEBUG_WRITE_VARIABLE_ASCIIW 1504
#define IDS_CLIENT_DEBUG_READ_VARIABLE 1505
#define IDS_CLIENT_DEBUG_READ_VARIABLEW 1506
#define IDS_CLIENT_DEBUG_WRITE_VARIABLE 1507
#define IDS_CLIENT_DEBUG_WRITE_VARIABLEW 1508
#define IDS_CLIENT_INPUT_MESSAGE        1600
#define IDS_CLIENT_OUTPUT_MESSAGE       1601

#define IDC_TITLE                       1001
#define IDC_INFO                        1002
#define IDC_DISCLAIMER                  1003
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         32780
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
